services:
  postgres:
    image: postgres:17
    container_name: itapass-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: itapass
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itapass

    ports:
      - "5432:5432"

    volumes:
      - itapass_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d itapass"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  itapass_postgres_data: